/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_presentacion;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import lib_clases.departamento;
import lib_gestion.gestion;
import lib_reporte.Form_reporte_concentrado;
import lib_reporte.Form_reporte_departamento;

/**
 *
 * @author juliovicente
 */
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_principal
     */
    gestion gestionM;
    int iddepartamento = -1;
    ArrayList<departamento> departamentos;
    public frm_principal() {
        initComponents();
        gestionM = new gestion();
        departamentos = new ArrayList<departamento>();
    }
    public frm_principal(int identidad) throws SQLException {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        gestionM = new gestion();        
        
//        Combo_departamentos.removeAllItems();
       Identidad = identidad;
        ActualizaDepa();
//        for(departamento objeto: departamentos)
//        {
//            Combo_departamentos.addItem(objeto.getDescripcion());
//        }
//        
    }

    int Identidad=0;
    public void ActualizaDepa()
    {
        try{
        departamentos = gestionM.ListarDepartamentos_Entidad(Identidad);
        for (int i = 0; i < jMenu1.getItemCount(); i++) {
            JMenuItem s = jMenu1.getItem(i);
            Boolean estado = false;
            for(departamento objeto: departamentos)
            {
                if (s.getText().equals(objeto.getDescripcion()))
                    estado= true;
            }
            s.setEnabled(estado);
        }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getCause());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemUSUARIO = new javax.swing.JMenuItem();
        jMenuItemPACIENTES = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSALIR = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemEMERGENCIA = new javax.swing.JMenuItem();
        jMenuItemCIRUGIA = new javax.swing.JMenuItem();
        jMenuItemGINECOBSTETRICIA = new javax.swing.JMenuItem();
        jMenuItemTRAUMATOLOGIA = new javax.swing.JMenuItem();
        jMenuItemMEDICINAINTERNA = new javax.swing.JMenuItem();
        jMenuItemPEDIATRIA = new javax.swing.JMenuItem();
        jMenuItemUCI = new javax.swing.JMenuItem();
        jMenuItemINFECTOLOGIA = new javax.swing.JMenuItem();
        jMenuItemUNIDADQUEMADOS = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDEPARTAMENTO = new javax.swing.JMenuItem();
        jMenuItemCONCENTRADO = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemACERCADE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Hospital Rafeal Rodriguez Zambrano");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Control de Dietas");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-2.jpg"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(164, 164, 164))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                        .addGap(135, 135, 135))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(281, 281, 281))
        );
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu4.setText("ARCHIVO");
        jMenu4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jMenuItemUSUARIO.setText("USUARIO");
        jMenuItemUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUSUARIOActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemUSUARIO);

        jMenuItemPACIENTES.setText("PACIENTES");
        jMenu4.add(jMenuItemPACIENTES);

        jMenuItem1.setText("PERMISOS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator1);

        jMenuItemSALIR.setText("SALIR");
        jMenu4.add(jMenuItemSALIR);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("DEPARTAMENTOS");
        jMenu1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jMenu1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu1MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemEMERGENCIA.setText("EMERGENCIA");
        jMenuItemEMERGENCIA.setEnabled(false);
        jMenuItemEMERGENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEMERGENCIAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEMERGENCIA);

        jMenuItemCIRUGIA.setText("CIRUGIA");
        jMenuItemCIRUGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCIRUGIAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCIRUGIA);

        jMenuItemGINECOBSTETRICIA.setText("GINECO-OBSTETRICIA");
        jMenuItemGINECOBSTETRICIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGINECOBSTETRICIAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGINECOBSTETRICIA);

        jMenuItemTRAUMATOLOGIA.setText("TRAUMATOLOGIA");
        jMenuItemTRAUMATOLOGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTRAUMATOLOGIAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTRAUMATOLOGIA);

        jMenuItemMEDICINAINTERNA.setText("MEDICINA INTERNA");
        jMenuItemMEDICINAINTERNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMEDICINAINTERNAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMEDICINAINTERNA);

        jMenuItemPEDIATRIA.setText("PEDIATRIA");
        jMenuItemPEDIATRIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPEDIATRIAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPEDIATRIA);

        jMenuItemUCI.setText("UCI");
        jMenuItemUCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUCIActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUCI);

        jMenuItemINFECTOLOGIA.setText("INFECTOLOGIA");
        jMenuItemINFECTOLOGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemINFECTOLOGIAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemINFECTOLOGIA);

        jMenuItemUNIDADQUEMADOS.setText("UNIDAD DE QUEMADOS");
        jMenuItemUNIDADQUEMADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUNIDADQUEMADOSActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUNIDADQUEMADOS);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("REPORTES");
        jMenu2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jMenuItemDEPARTAMENTO.setText("DEPARTAMENTO");
        jMenuItemDEPARTAMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDEPARTAMENTOActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemDEPARTAMENTO);

        jMenuItemCONCENTRADO.setText("CONCENTRADO");
        jMenuItemCONCENTRADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCONCENTRADOActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCONCENTRADO);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("INFORMACIÓN");
        jMenu3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jMenuItemACERCADE.setText("ACERCA DE..");
        jMenuItemACERCADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemACERCADEActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemACERCADE);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private departamento buscarDepartamento(String texto){
        departamento dep = new departamento();
        for(departamento objeto: departamentos)
            {
                if (texto == null ? objeto.getDescripcion() == null : texto.equals(objeto.getDescripcion())) {
                    iddepartamento = objeto.getId();
                    return dep=objeto;
                }
            }
        return dep;
    }
    private void jMenuItemEMERGENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEMERGENCIAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemEMERGENCIAActionPerformed

    private void jMenuItemCIRUGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCIRUGIAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemCIRUGIAActionPerformed

    private void jMenuItemGINECOBSTETRICIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGINECOBSTETRICIAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemGINECOBSTETRICIAActionPerformed

    private void jMenuItemTRAUMATOLOGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTRAUMATOLOGIAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemTRAUMATOLOGIAActionPerformed

    private void jMenuItemMEDICINAINTERNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMEDICINAINTERNAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemMEDICINAINTERNAActionPerformed

    private void jMenuItemPEDIATRIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPEDIATRIAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemPEDIATRIAActionPerformed

    private void jMenuItemUCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUCIActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemUCIActionPerformed

    private void jMenuItemINFECTOLOGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemINFECTOLOGIAActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemINFECTOLOGIAActionPerformed

    private void jMenuItemUNIDADQUEMADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUNIDADQUEMADOSActionPerformed
        buscarDepartamento(evt.getActionCommand().toString());
        frm_proceso proceso = new frm_proceso(iddepartamento);           
        jDesktopPane1.add(proceso);
        proceso.setVisible(true); 
    }//GEN-LAST:event_jMenuItemUNIDADQUEMADOSActionPerformed

    private void jMenuItemDEPARTAMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDEPARTAMENTOActionPerformed
        Form_reporte_departamento frm_departamento= null;
        try {
            frm_departamento = new Form_reporte_departamento();
        } catch (SQLException ex) {
            Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(frm_departamento);
        frm_departamento.setVisible(true); 
    }//GEN-LAST:event_jMenuItemDEPARTAMENTOActionPerformed

    private void jMenuItemCONCENTRADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCONCENTRADOActionPerformed
        Form_reporte_concentrado frm_concentrado = new Form_reporte_concentrado(); 
        jDesktopPane1.add(frm_concentrado);
        frm_concentrado.setVisible(true); 
    }//GEN-LAST:event_jMenuItemCONCENTRADOActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Permisos frm_permiso = new Permisos();
        jDesktopPane1.add(frm_permiso);
        frm_permiso.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu1MenuKeyPressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenu1MenuKeyPressed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
         ActualizaDepa();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenuItemUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUSUARIOActionPerformed
        // TODO add your handling code here:
         frm_usuario frm_permiso = new frm_usuario();
        jDesktopPane1.add(frm_permiso);
        frm_permiso.setVisible(true);
                                    
    }//GEN-LAST:event_jMenuItemUSUARIOActionPerformed

    private void jMenuItemACERCADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemACERCADEActionPerformed
        // TODO add your handling code here:
        frm_info info = new frm_info();
        jDesktopPane1.add(info);
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItemACERCADEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_principal(1).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemACERCADE;
    private javax.swing.JMenuItem jMenuItemCIRUGIA;
    private javax.swing.JMenuItem jMenuItemCONCENTRADO;
    private javax.swing.JMenuItem jMenuItemDEPARTAMENTO;
    private javax.swing.JMenuItem jMenuItemEMERGENCIA;
    private javax.swing.JMenuItem jMenuItemGINECOBSTETRICIA;
    private javax.swing.JMenuItem jMenuItemINFECTOLOGIA;
    private javax.swing.JMenuItem jMenuItemMEDICINAINTERNA;
    private javax.swing.JMenuItem jMenuItemPACIENTES;
    private javax.swing.JMenuItem jMenuItemPEDIATRIA;
    private javax.swing.JMenuItem jMenuItemSALIR;
    private javax.swing.JMenuItem jMenuItemTRAUMATOLOGIA;
    private javax.swing.JMenuItem jMenuItemUCI;
    private javax.swing.JMenuItem jMenuItemUNIDADQUEMADOS;
    private javax.swing.JMenuItem jMenuItemUSUARIO;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
