/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_presentacion;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.SSLEngineResult;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lib_clases.departamento;
import lib_clases.dieta;
import lib_clases.dprincipal;
import lib_clases.entidad;
import lib_clases.principal;
import lib_clases.tentidad;
import lib_datos.NpgSqlConnection;
import lib_gestion.gestion;
import lib_reporte.Form_reporte_departamento;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LUIS
 */
public class frm_proceso extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_proceso
     */
    public frm_proceso() {
        initComponents();
        setClosable(true);
    }

    public frm_proceso(int iddepartamento,String descripcion) {
        initComponents();
        setClosable(true);
        gestionM = new gestion();
        dprinci = new ArrayList<dprincipal>();
        gentidad = new entidad();
        gprincipal = new principal();
        
        gtentida = new tentidad();
        dep = new departamento();
        dep.setId(iddepartamento);
        dep.setDescripcion(descripcion);
        gprincipal.setIddertamento(dep);
        gprincipal.setNum_cama("0");
        Nuevo();
        aniadeLista();
        lbldepartamento.setText(dep.getDescripcion());
        
        estado = true;
        

    }
    tentidad gtentida;
    gestion gestionM;
    ArrayList<dprincipal> dprinci;
    entidad gentidad;
    principal gprincipal;
    departamento dep;
    boolean estado= false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbx1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbx2 = new javax.swing.JList();
        dtfecha = new com.toedter.calendar.JCalendar();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbx3 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bttactualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lbldepartamento = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtApelliNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dtFechanaci = new com.toedter.calendar.JDateChooser();
        txtidentificacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbxHorario = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cbxLatanciaMaterna = new javax.swing.JCheckBox();
        cbxNPO = new javax.swing.JCheckBox();
        cbxAcompaniante = new javax.swing.JCheckBox();
        cbxHiposodica = new javax.swing.JCheckBox();
        cbxHipograsa = new javax.swing.JCheckBox();
        cbxPedi611 = new javax.swing.JCheckBox();
        cbxPedi1259 = new javax.swing.JCheckBox();
        cbxPedi59 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        cbxLiquiAca = new javax.swing.JCheckBox();
        cbxLiquiEst = new javax.swing.JCheckBox();
        cbxLiquiAmp = new javax.swing.JCheckBox();
        cbxBlaGast = new javax.swing.JCheckBox();
        cbxBlaInt = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        cbxBlaMec = new javax.swing.JCheckBox();
        cbxTurGas = new javax.swing.JCheckBox();
        cbxIle1 = new javax.swing.JCheckBox();
        cbxIle2 = new javax.swing.JCheckBox();
        cbxIle3 = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        cbxHipercalorica = new javax.swing.JCheckBox();
        cbxHipeHipe = new javax.swing.JCheckBox();
        cbxHipoCal = new javax.swing.JCheckBox();
        cbxHipoProEst = new javax.swing.JCheckBox();
        cbxHipoproteica = new javax.swing.JCheckBox();
        cbxHiperp = new javax.swing.JCheckBox();
        cbxHipohidro = new javax.swing.JCheckBox();
        cbxHipoHipo = new javax.swing.JCheckBox();
        cbxHipoHipe = new javax.swing.JCheckBox();
        cbxSinGlu = new javax.swing.JCheckBox();

        jSplitPane1.setDividerLocation(290);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 638));

        jLabel4.setText("FECHA:");

        lbx1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbx1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbx1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lbx1);

        lbx2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbx2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbx2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lbx2);

        dtfecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtfechaPropertyChange(evt);
            }
        });

        lbx3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbx3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbx3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lbx3);

        jLabel2.setText("Desayuno");

        jLabel5.setText("Almuerzo");

        jLabel9.setText("Merienda");

        bttactualizar.setBackground(new java.awt.Color(255, 0, 0));
        bttactualizar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        bttactualizar.setText("Actualizar");
        bttactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(bttactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(dtfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttactualizar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jSplitPane2.setDividerLocation(98);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel3.setBackground(new java.awt.Color(248, 200, 115));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("HOSPITAL DR. RAFAEL RODRIGUEZ ZAMBRANO");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("REGISTROS DE DIETAS");

        jButton4.setText("VISTA PREVIA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lbldepartamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldepartamento.setText("jLabel11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(263, 263, 263))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbldepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(163, 163, 163))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbldepartamento)
                .addGap(7, 7, 7))
        );

        jLabel1.getAccessibleContext().setAccessibleName("TABLA DE REGISTROS");

        jSplitPane2.setTopComponent(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel7.setText("APELLIDOS Y NOMBRES:");

        jLabel6.setText("CÉDULA:");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dtFechanaci.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtFechanaciPropertyChange(evt);
            }
        });

        txtidentificacion.setName("txtcedula"); // NOI18N
        txtidentificacion.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtidentificacionInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentificacionActionPerformed(evt);
            }
        });
        txtidentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidentificacionKeyPressed(evt);
            }
        });

        jLabel8.setText("NÚMERO CAMA:");

        jLabel10.setText("FECHA NACIMIENTO:");

        cbxHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desayuno", "Almuerzo", "Merienda", " " }));

        jLabel11.setText("HORARIO:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApelliNom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dtFechanaci, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtidentificacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxHorario, 0, 116, Short.MAX_VALUE)
                            .addComponent(txtcama))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(2, 2, 2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFechanaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(txtcama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApelliNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BASAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        cbxLatanciaMaterna.setText("Lactancia Materna");
        cbxLatanciaMaterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLatanciaMaternaActionPerformed(evt);
            }
        });

        cbxNPO.setText("NPO");

        cbxAcompaniante.setText("General");

        cbxHiposodica.setText("Hiposodica");

        cbxHipograsa.setText("Hipograsa ");

        cbxPedi611.setText("Pediatría 6 a 11 meses");

        cbxPedi1259.setText("Pediatría 12 a 59 meses");

        cbxPedi59.setText("Pediatría 5 a 9 años");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbxLatanciaMaterna)
                        .addGap(18, 18, 18)
                        .addComponent(cbxHipograsa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNPO)
                            .addComponent(cbxAcompaniante)
                            .addComponent(cbxHiposodica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPedi1259)
                            .addComponent(cbxPedi611)
                            .addComponent(cbxPedi59))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbxPedi611)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPedi1259)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPedi59))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxLatanciaMaterna)
                            .addComponent(cbxHipograsa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxNPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxAcompaniante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxHiposodica)))
                .addGap(15, 15, 15))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSCICIÓN\t\t\t ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        cbxLiquiAca.setText("Líquida acalórica ");

        cbxLiquiEst.setText("Líquida Estricta");

        cbxLiquiAmp.setText("Líquida Amplia");

        cbxBlaGast.setText("Blanda Gástrica");

        cbxBlaInt.setText("Blanda Intestinal");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxLiquiAca)
                    .addComponent(cbxLiquiEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxBlaInt)
                    .addComponent(cbxLiquiAmp)
                    .addComponent(cbxBlaGast))
                .addGap(151, 151, 151))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLiquiAca)
                    .addComponent(cbxLiquiAmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLiquiEst)
                    .addComponent(cbxBlaGast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxBlaInt)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TEXTURA MODIFICADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        cbxBlaMec.setText("Blanda mecánica Geriátrica");

        cbxTurGas.setText("Turmix: SNG y Gastrotomía ");

        cbxIle1.setText("Ileostomía fase 1");
        cbxIle1.setActionCommand("");

        cbxIle2.setText("Ileostomía fase 2 ");

        cbxIle3.setText("Ileostomía fase 3");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTurGas)
                    .addComponent(cbxBlaMec))
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxIle1)
                    .addComponent(cbxIle2)
                    .addComponent(cbxIle3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cbxBlaMec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTurGas))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbxIle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxIle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxIle3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TERAPÉUTICAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        cbxHipercalorica.setText("Hipercalorica");

        cbxHipeHipe.setText("HIPERCALORICA-HIPERPROTEICA");

        cbxHipoCal.setText("Hipo caloríca ");
        cbxHipoCal.setActionCommand("");

        cbxHipoProEst.setText("Hipo Proteica estricta ");

        cbxHipoproteica.setText("Hipoproteica");

        cbxHiperp.setText("Hiperproteica");

        cbxHipohidro.setText("Hipohidrocarbonada");

        cbxHipoHipo.setText("Hipohidrocarbonada hipoproteica");

        cbxHipoHipe.setText("Hipohidrocarbonada Hiperproteica");

        cbxSinGlu.setText("Sin gluten");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxHipoproteica)
                    .addComponent(cbxHipercalorica)
                    .addComponent(cbxHipeHipe)
                    .addComponent(cbxHipoCal)
                    .addComponent(cbxHipoProEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSinGlu)
                            .addComponent(cbxHipoHipe)
                            .addComponent(cbxHipoHipo)
                            .addComponent(cbxHipohidro))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(cbxHiperp)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHipoCal)
                    .addComponent(cbxHiperp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHipoProEst)
                    .addComponent(cbxHipohidro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHipoproteica)
                    .addComponent(cbxHipoHipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHipercalorica)
                    .addComponent(cbxHipoHipe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSinGlu)
                    .addComponent(cbxHipeHipe)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(23, 23, 23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        jSplitPane2.setBottomComponent(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validar()
    {
        int contador =0;
        for (dprincipal dpl: dprinci) {
            if (dpl.getActivado()) {
                contador++;
            }
        }
        if (contador==0 || contador>2) {
            return false;
        }else { return true;}
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            asignarInterfasAGestion();
            if(validar()){
            if (gprincipal.getId() == 0) {
                int i = gprincipal.getIdhorario();
                //Repeticion en por jornada
                while (i <= 3) {
                    gprincipal.setIdhorario(i);
                    gestionM.Insertar(gentidad, gprincipal, dprinci);
                    i++;
                }
            } else {
                gestionM.Actualizar(gentidad, gprincipal, dprinci);
            }
            
            aniadeLista();
            Nuevo();
            }else 
            {
                JOptionPane.showMessageDialog(null, "Debe selecciona minimo 1 elemento para continuar");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtidentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidentificacionKeyPressed
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == 10) {

                gentidad = gestionM.listapersona(txtidentificacion.getText());
                if (gentidad.getDescripcion() != null) {
                    txtApelliNom.setText(gentidad.getDescripcion());
                    txtidentificacion.setText(gentidad.getIdentificacion());
                    dtFechanaci.setDate(gentidad.getFechanaci());
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_txtidentificacionKeyPressed

    private void Nuevo() {
        dprinci = new ArrayList<dprincipal>();
        gentidad = new entidad();
        gentidad.setId(0);
        gentidad.setFechaNaci(new Date());
        gprincipal.setId(0);
        gprincipal.setIdestado(0);
        gprincipal.setNum_cama(String.valueOf(Integer.parseInt(gprincipal.getNum_cama())+1));
        gprincipal.setObservacion("");
        gtentida = new tentidad();
        gtentida.setId(1);
        gentidad.setIdtentidad(gtentida);
        gentidad.setId(0);
        cbxHorario.setSelectedIndex(0);
        asignarGestionAInterface();

    }
    private void txtidentificacionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtidentificacionInputMethodTextChanged
        // TODO add your handling code here:
        JOptionPane.showInputDialog(evt.getText());
    }//GEN-LAST:event_txtidentificacionInputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        aniadeLista();
        Nuevo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbx3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbx3MouseClicked
        // TODO add your handling code here:
        gentidad = lentar.get(lbx3.getSelectedIndex());
        gprincipal.setId(gentidad.getId());
        Cargar();
    }//GEN-LAST:event_lbx3MouseClicked

    private void lbx2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbx2MouseClicked
        // TODO add your handling code here:
        gentidad = lenmed.get(lbx2.getSelectedIndex());
        gprincipal.setId(gentidad.getId());
        Cargar();
    }//GEN-LAST:event_lbx2MouseClicked

    private void lbx1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbx1MouseClicked
        // TODO add your handling code here:
        gentidad = lenma.get(lbx1.getSelectedIndex());
        gprincipal.setId(gentidad.getId());
        Cargar();
        
    }//GEN-LAST:event_lbx1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            asignarInterfasAGestion();
            gprincipal.setIdestado(1);
            gestionM.Actualizar(gentidad, gprincipal, dprinci);
            aniadeLista();
            Nuevo();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void bttactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttactualizarActionPerformed
        // TODO add your handling code here:
        try {
            gestionM.listar_all(3, dtfecha.getDate());
            aniadeLista();
            Nuevo();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getSQLState());
        }
    }//GEN-LAST:event_bttactualizarActionPerformed

    private void txtidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentificacionActionPerformed

    NpgSqlConnection conn = new NpgSqlConnection();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String dir = System.getProperty("user.dir") + "/reporte/report_departamento.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            Map parametro = new HashMap();
            parametro.put("FechaDesde","'"+new SimpleDateFormat("yyyy-MM-dd").format(this.dtfecha.getDate())+"'");
            parametro.put("FechaHasta", "'"+new SimpleDateFormat("yyyy-MM-dd").format(this.dtfecha.getDate())+"'");
            parametro.put("iddepartamento", gprincipal.getIddertamento().getId());
            parametro.put("departamento", gprincipal.getIddertamento().getDescripcion());
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, parametro, conn.getConection());
            JasperViewer.viewReport(mostrarReporte, false);
        } catch (SQLException ex) {
            Logger.getLogger(Form_reporte_departamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Form_reporte_departamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dtfechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtfechaPropertyChange
        // TODO add your handling code here:
        if (estado) {
            aniadeLista();
        }
        
    }//GEN-LAST:event_dtfechaPropertyChange

    private void cbxLatanciaMaternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLatanciaMaternaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxLatanciaMaternaActionPerformed

    private void dtFechanaciPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtFechanaciPropertyChange
        // TODO add your handling code here:

            Calendar birth = new GregorianCalendar();
            Calendar today = new GregorianCalendar();
            int age = 0;
            int factor = 0;
            Date birthDate = dtFechanaci.getDate();
            Date currentDate = new Date(); //current date
            birth.setTime(birthDate);
            today.setTime(currentDate);
//            if (today.get(Calendar.MONTH) <= birth.get(Calendar.MONTH)) {
//                if (today.get(Calendar.MONTH) == birth.get(Calendar.MONTH)) {
//                    if (today.get(Calendar.DATE) > birth.get(Calendar.DATE)) {
//                        factor = -1; //Aun no celebra su cumpleaÃ±os
//                    }
//                } else {
//                    factor = -1; //Aun no celebra su cumpleaÃ±os
//                }
//            }
            age = (today.get(Calendar.YEAR) - birth.get(Calendar.YEAR));
        if (age<1) {
            cbxPedi611.setSelected(true);
        }else
        {
            if (age<5) {
                cbxPedi1259.setSelected(true);
            }
            else
            {
                if (age<9) {
                    cbxPedi59.setSelected(true);
                }else{
                    cbxPedi611.setSelected(false);
                    cbxPedi1259.setSelected(false);
                    cbxPedi59.setSelected(false);
                }
                
            }
        }
    }//GEN-LAST:event_dtFechanaciPropertyChange
    private void Cargar() {
        try {
            gprincipal = gestionM.Listar_principal(gprincipal.getId());
            gentidad = gprincipal.getIdentidad();
            dprinci = gestionM.Lista_dprincipal(gprincipal);
            asignarGestionAInterface();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private dprincipal aniadir(Integer id, Integer iddieta, boolean cbx, Integer estado) {
        dprincipal dprin = new dprincipal();
        dieta die = new dieta();
        dprin.setId(id);
        die.setId(iddieta);
        dprin.setIddieta(die);
        dprin.setActivado(cbx);
        dprin.setIdestado(estado);
        return dprin;
    }

    private void asignarInterfasAGestion() {

        if (gprincipal.getId() == 0) {
            if (gentidad.getId() == 0) {
                gentidad.setIdentificacion(txtidentificacion.getText());
                gentidad.setDescripcion(this.txtApelliNom.getText());
                gentidad.setFechaNaci(dtFechanaci.getDate());
            }
            gprincipal.setFecha(dtfecha.getDate());
            //gprincipal.setIdhorario();
            gprincipal.setIdhorario(cbxHorario.getSelectedIndex()+1);
//            Calendar cald = Calendar.getInstance();
//            if (cald.get(Calendar.HOUR_OF_DAY) < 10) {
//                gprincipal.setIdhorario(1);
//            } else {
//                if (cald.get(Calendar.HOUR_OF_DAY) < 14) {
//                    gprincipal.setIdhorario(2);
//                } else {
//                    if (cald.get(Calendar.HOUR_OF_DAY) < 18) {
//                        gprincipal.setIdhorario(3);
//                    }
//                }
//            }
            gprincipal.setNum_cama(this.txtcama.getText());
            gprincipal.setObservacion(this.txtObservacion.getText());
            dprinci = new ArrayList<dprincipal>();
            dprinci.add(aniadir(0, 1, this.cbxLatanciaMaterna.isSelected(), 0));
            dprinci.add(aniadir(0, 2, this.cbxNPO.isSelected(), 0));
            dprinci.add(aniadir(0, 3, this.cbxAcompaniante.isSelected(), 0));
            dprinci.add(aniadir(0, 4, this.cbxHiposodica.isSelected(), 0));
            dprinci.add(aniadir(0, 5, this.cbxHipograsa.isSelected(), 0));
            dprinci.add(aniadir(0, 6, this.cbxPedi611.isSelected(), 0));
            dprinci.add(aniadir(0, 7, this.cbxPedi1259.isSelected(), 0));
            dprinci.add(aniadir(0, 8, this.cbxPedi59.isSelected(), 0));
//            dprinci.add(aniadir(0, 9, this.cbxPedi26.isSelected(), 0));
//            dprinci.add(aniadir(0, 10, this.cbxPedi711.isSelected(), 0));
            dprinci.add(aniadir(0, 9, this.cbxLiquiAca.isSelected(), 0));
            dprinci.add(aniadir(0,10, this.cbxLiquiEst.isSelected(), 0));
            dprinci.add(aniadir(0, 11, this.cbxLiquiAmp.isSelected(), 0));
            dprinci.add(aniadir(0, 12, this.cbxBlaGast.isSelected(), 0));
            dprinci.add(aniadir(0, 13, this.cbxBlaInt.isSelected(), 0));
            dprinci.add(aniadir(0, 14, this.cbxBlaMec.isSelected(), 0));
            dprinci.add(aniadir(0, 15, this.cbxTurGas.isSelected(), 0));
            dprinci.add(aniadir(0, 16, this.cbxIle1.isSelected(), 0));
            dprinci.add(aniadir(0, 17, this.cbxIle2.isSelected(), 0));
            dprinci.add(aniadir(0, 18, this.cbxIle3.isSelected(), 0));
            dprinci.add(aniadir(0, 19, this.cbxHipoCal.isSelected(), 0));
            dprinci.add(aniadir(0, 20, this.cbxHipoProEst.isSelected(), 0));
            dprinci.add(aniadir(0, 21, this.cbxHipoproteica.isSelected(), 0));
            dprinci.add(aniadir(0, 22, this.cbxHipercalorica.isSelected(), 0));
            dprinci.add(aniadir(0, 23, this.cbxHipeHipe.isSelected(), 0));
            dprinci.add(aniadir(0, 24, this.cbxHiperp.isSelected(), 0));
            dprinci.add(aniadir(0, 25, this.cbxHipohidro.isSelected(), 0));
            dprinci.add(aniadir(0, 26, this.cbxHipoHipo.isSelected(), 0));
            dprinci.add(aniadir(0, 27, this.cbxHipoHipe.isSelected(), 0));
            dprinci.add(aniadir(0, 28, this.cbxSinGlu.isSelected(), 0));
                        
        } else {
            ArrayList<dprincipal> copy = new ArrayList<dprincipal>();
            copy = dprinci;
            dprinci = new ArrayList<dprincipal>();
            gprincipal.setNum_cama(this.txtcama.getText());
            gprincipal.setFecha(dtfecha.getDate());
            gprincipal.setIdhorario(cbxHorario.getSelectedIndex()+1);
            gprincipal.setObservacion(this.txtObservacion.getText());
            dprinci.add(aniadir(copy.get(0).getId(), 1, this.cbxLatanciaMaterna.isSelected(), 0));
            dprinci.add(aniadir(copy.get(1).getId(), 2, this.cbxNPO.isSelected(), 0));
            dprinci.add(aniadir(copy.get(2).getId(), 3, this.cbxAcompaniante.isSelected(), 0));
            dprinci.add(aniadir(copy.get(3).getId(), 4, this.cbxHiposodica.isSelected(), 0));
            dprinci.add(aniadir(copy.get(4).getId(), 5, this.cbxHipograsa.isSelected(), 0));
            dprinci.add(aniadir(copy.get(5).getId(), 6, this.cbxPedi611.isSelected(), 0));
            dprinci.add(aniadir(copy.get(6).getId(), 7, this.cbxPedi1259.isSelected(), 0));
            dprinci.add(aniadir(copy.get(7).getId(), 8, this.cbxPedi59.isSelected(), 0));
            dprinci.add(aniadir(copy.get(8).getId(), 9, this.cbxLiquiAca.isSelected(), 0));
            dprinci.add(aniadir(copy.get(9).getId(), 10, this.cbxLiquiEst.isSelected(), 0));
            dprinci.add(aniadir(copy.get(10).getId(), 11, this.cbxLiquiAmp.isSelected(), 0));
            dprinci.add(aniadir(copy.get(11).getId(), 12, this.cbxBlaGast.isSelected(), 0));
            dprinci.add(aniadir(copy.get(12).getId(), 13, this.cbxBlaInt.isSelected(), 0));
            dprinci.add(aniadir(copy.get(13).getId(), 14, this.cbxBlaMec.isSelected(), 0));
            dprinci.add(aniadir(copy.get(14).getId(), 15, this.cbxTurGas.isSelected(), 0));
            dprinci.add(aniadir(copy.get(15).getId(), 16, this.cbxIle1.isSelected(), 0));
            dprinci.add(aniadir(copy.get(16).getId(), 17, this.cbxIle2.isSelected(), 0));
            dprinci.add(aniadir(copy.get(17).getId(), 18, this.cbxIle3.isSelected(), 0));
            dprinci.add(aniadir(copy.get(18).getId(), 19, this.cbxHipoCal.isSelected(), 0));
            dprinci.add(aniadir(copy.get(19).getId(), 20, this.cbxHipoProEst.isSelected(), 0));
            dprinci.add(aniadir(copy.get(20).getId(), 21, this.cbxHipoproteica.isSelected(), 0));
            dprinci.add(aniadir(copy.get(21).getId(), 22, this.cbxHipercalorica.isSelected(), 0));
            dprinci.add(aniadir(copy.get(22).getId(), 23, this.cbxHipeHipe.isSelected(), 0));
            dprinci.add(aniadir(copy.get(23).getId(), 24, this.cbxHiperp.isSelected(), 0));
            dprinci.add(aniadir(copy.get(24).getId(), 25, this.cbxHipohidro.isSelected(), 0));
            dprinci.add(aniadir(copy.get(25).getId(), 26, this.cbxHipoHipo.isSelected(), 0));
            dprinci.add(aniadir(copy.get(26).getId(), 27, this.cbxHipoHipe.isSelected(), 0));
            dprinci.add(aniadir(copy.get(27).getId(), 28, this.cbxSinGlu.isSelected(), 0));
//            dprinci.add(aniadir(copy.get(28).getId(), 29, this.cbxBlaMec.isSelected(), 0));
//            dprinci.add(aniadir(copy.get(29).getId(), 30, this.cbxTurGas.isSelected(), 0));
        }

    }
    ArrayList<entidad> lenma;
    ArrayList<entidad> lenmed;
    ArrayList<entidad> lentar;

    private DefaultListModel<String> datas(ArrayList<entidad> lista) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (entidad enti : lista) {
            entidad eg = new entidad();
            eg = enti;
            String data = eg.getDescripcion();
            model.addElement(data);
            //model.addElement(eg.getDescripcion());
        }
        return model;
    }
 
    private void aniadeLista() {
        try {
            lenma = new ArrayList<entidad>();
            lenmed = new ArrayList<entidad>();
            lentar = new ArrayList<entidad>();
            lenma = gestionM.ListarEntidad(1, dtfecha.getDate(),dep.getId());
            lenmed = gestionM.ListarEntidad(2, dtfecha.getDate(),dep.getId());
            lentar = gestionM.ListarEntidad(3, dtfecha.getDate(),dep.getId());
            lbx1.setModel(datas(lenma));
            lbx2.setModel(datas(lenmed));
            lbx3.setModel(datas(lentar));
            if (lenma.size()!=0) {
                bttactualizar.setEnabled(false);
            }else {bttactualizar.setEnabled(true);}

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getSQLState());
        }
    }

    private void asignarGestionAInterface() {
        this.txtApelliNom.setText(gentidad.getDescripcion());
        this.txtidentificacion.setText(gentidad.getIdentificacion());
        this.dtFechanaci.setDate(gentidad.getFechanaci());
        this.txtcama.setText(gprincipal.getNum_cama());
        this.txtObservacion.setText(gprincipal.getObservacion());
        
        if (gprincipal.getId() != 0) {
            this.cbxHorario.setSelectedIndex(gprincipal.getIdhorario()-1);
            this.cbxLatanciaMaterna.setSelected(dprinci.get(0).getActivado());
            this.cbxNPO.setSelected(dprinci.get(1).getActivado());
            this.cbxAcompaniante.setSelected(dprinci.get(2).getActivado());
            this.cbxHiposodica.setSelected(dprinci.get(3).getActivado());
            this.cbxHipograsa.setSelected(dprinci.get(4).getActivado());
            this.cbxPedi611.setSelected(dprinci.get(5).getActivado());
            this.cbxPedi1259.setSelected(dprinci.get(6).getActivado());
            this.cbxPedi59.setSelected(dprinci.get(7).getActivado());
//            this.cbxPedi26.setSelected(dprinci.get(8).getActivado());
//            this.cbxPedi711.setSelected(dprinci.get(9).getActivado());
            this.cbxLiquiAca.setSelected(dprinci.get(8).getActivado());
            this.cbxLiquiEst.setSelected(dprinci.get(9).getActivado());
            this.cbxLiquiAmp.setSelected(dprinci.get(10).getActivado());
            this.cbxBlaGast.setSelected(dprinci.get(11).getActivado());
            this.cbxBlaInt.setSelected(dprinci.get(12).getActivado());
            this.cbxBlaMec.setSelected(dprinci.get(13).getActivado());
            this.cbxTurGas.setSelected(dprinci.get(14).getActivado());
            this.cbxIle1.setSelected(dprinci.get(15).getActivado());
            this.cbxIle2.setSelected(dprinci.get(16).getActivado());
            this.cbxIle3.setSelected(dprinci.get(17).getActivado());
            this.cbxHipoCal.setSelected(dprinci.get(18).getActivado());
            this.cbxHipoProEst.setSelected(dprinci.get(19).getActivado());
            this.cbxHipoproteica.setSelected(dprinci.get(20).getActivado());
            this.cbxHipercalorica.setSelected(dprinci.get(21).getActivado());
            this.cbxHipeHipe.setSelected(dprinci.get(22).getActivado());
            this.cbxHiperp.setSelected(dprinci.get(23).getActivado());
            this.cbxHipohidro.setSelected(dprinci.get(24).getActivado());
            this.cbxHipoHipo.setSelected(dprinci.get(25).getActivado());
            this.cbxHipoHipe.setSelected(dprinci.get(26).getActivado());
            this.cbxSinGlu.setSelected(dprinci.get(27).getActivado());
        } else {
            this.cbxHorario.setSelectedIndex(gprincipal.getIdhorario());
            this.cbxLatanciaMaterna.setSelected(false);
            this.cbxNPO.setSelected(false);
            this.cbxAcompaniante.setSelected(false);
            this.cbxHiposodica.setSelected(false);
            this.cbxHipograsa.setSelected(false);
            this.cbxPedi611.setSelected(false);
            this.cbxPedi1259.setSelected(false);
            this.cbxPedi59.setSelected(false);
//            this.cbxPedi26.setSelected(false);
//            this.cbxPedi711.setSelected(false);
            this.cbxLiquiAca.setSelected(false);
            this.cbxLiquiEst.setSelected(false);
            this.cbxLiquiAmp.setSelected(false);
            this.cbxBlaGast.setSelected(false);
            this.cbxBlaInt.setSelected(false);
            this.cbxHipoCal.setSelected(false);
            this.cbxHipoProEst.setSelected(false);
            this.cbxHipoHipo.setSelected(false);
            this.cbxHipoHipe.setSelected(false);
            this.cbxHipeHipe.setSelected(false);
            this.cbxHiperp.setSelected(false);
            this.cbxHipohidro.setSelected(false);
            this.cbxHipoproteica.setSelected(false);
            this.cbxHipercalorica.setSelected(false);
            this.cbxSinGlu.setSelected(false);
            this.cbxIle1.setSelected(false);
            this.cbxIle2.setSelected(false);
            this.cbxIle3.setSelected(false);
            this.cbxBlaMec.setSelected(false);
            this.cbxTurGas.setSelected(false);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_proceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_proceso(1,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttactualizar;
    private javax.swing.JCheckBox cbxAcompaniante;
    private javax.swing.JCheckBox cbxBlaGast;
    private javax.swing.JCheckBox cbxBlaInt;
    private javax.swing.JCheckBox cbxBlaMec;
    private javax.swing.JCheckBox cbxHipeHipe;
    private javax.swing.JCheckBox cbxHipercalorica;
    private javax.swing.JCheckBox cbxHiperp;
    private javax.swing.JCheckBox cbxHipoCal;
    private javax.swing.JCheckBox cbxHipoHipe;
    private javax.swing.JCheckBox cbxHipoHipo;
    private javax.swing.JCheckBox cbxHipoProEst;
    private javax.swing.JCheckBox cbxHipograsa;
    private javax.swing.JCheckBox cbxHipohidro;
    private javax.swing.JCheckBox cbxHipoproteica;
    private javax.swing.JCheckBox cbxHiposodica;
    private javax.swing.JComboBox cbxHorario;
    private javax.swing.JCheckBox cbxIle1;
    private javax.swing.JCheckBox cbxIle2;
    private javax.swing.JCheckBox cbxIle3;
    private javax.swing.JCheckBox cbxLatanciaMaterna;
    private javax.swing.JCheckBox cbxLiquiAca;
    private javax.swing.JCheckBox cbxLiquiAmp;
    private javax.swing.JCheckBox cbxLiquiEst;
    private javax.swing.JCheckBox cbxNPO;
    private javax.swing.JCheckBox cbxPedi1259;
    private javax.swing.JCheckBox cbxPedi59;
    private javax.swing.JCheckBox cbxPedi611;
    private javax.swing.JCheckBox cbxSinGlu;
    private javax.swing.JCheckBox cbxTurGas;
    private com.toedter.calendar.JDateChooser dtFechanaci;
    private com.toedter.calendar.JCalendar dtfecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lbldepartamento;
    private javax.swing.JList lbx1;
    private javax.swing.JList lbx2;
    private javax.swing.JList lbx3;
    private javax.swing.JTextField txtApelliNom;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtcama;
    private javax.swing.JTextField txtidentificacion;
    // End of variables declaration//GEN-END:variables
}
